name: atmospheric_particles
description: "A lightweight and customizable Flutter package for creating beautiful particle animations and atmospheric effects in the background of any widget."
version: 0.3.4
homepage: https://github.com/fatihsonmez/atmospheric_particles
repository: https://github.com/fatihsonmez/atmospheric_particles

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
